name = "backend"
compatibility_date = "2023-12-01"

[vars]

DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZDA0ZjUwZTktYzdiZS00OTRkLWIxNTItNjk4YWRmOWQzNDBiIiwidGVuYW50X2lkIjoiYWQ4ZDYwMTY5ZDlkYzA3ZWNiYmFkNDhmYjc4YjA2MjllYjUwZWJhNzAxNDEyNDIwZGI5MDM2YTNlNDYyNWQwNCIsImludGVybmFsX3NlY3JldCI6IjgxOTlmZGI5LTZiMTMtNDdjMC1iNmNiLTBiMjM1MGEwOTk0YyJ9.QxbztZCVrtCj2hfTWJ2zkcj_evBtKkSWKgzWrbTu3-c"

JWT_SECRET="Medium"